#! /usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'irb'

require File.join(File.dirname(__FILE__), '..', 'castronaut')

Castronaut.config = Castronaut::Configuration.load(File.join(File.dirname(__FILE__), '..', 'config', 'castronaut.example.yml'))

IRB.start(__FILE__)
